### ISSUE TITLE
[FEAT] Platform specific tag suffixes

### ISSUE THREAD

**Issue by JWCS** [ubuntu-rocks/chiselled-jre#343]
**Is your feature request related to a problem? Please describe.**
When building multi-arch builds, pulling and storing locally both architectures of the upstream image is difficult without tagged platform differences.

**Describe the solution you'd like**
Could a platform suffix be added to the image tags?
Ex ubuntu/jre:8-22.04_edge_36-{arm64|amd64}

**Describe alternatives you've considered**
Pre-build steps to pull target image/platform, then re-tag to specify platform.

**Additional context**
There seems to be a lot of spam in the issues page...

**Comment by cjdcordeiro** [comment]
Hi @JWCS 

thanks for using the jre image.
I understand the request, and I ack that is a common practice for some images out there.

However, that is not our distribution strategy. When built for multiple architectures, our images are shipped with a single tag and a manifest list. That should simplify their usage, since you don't need to tailor the tag name based on the architecture, but simply let your container runtime infer the underlying host's architecture and pull the right manifest from the `8-22.04_edge` tag.

And, if for some reason, you need to have multiple arch images within the same host, you can simply tell your container runtime which arch to pull for. Example: `docker pull --platform arm64 ubuntu/jre:8-22.04_edge`

I hope this helps
